import javafx.application.Application;
import javafx.scene.control.*;
import javafx.scene.input.KeyCode;
import javafx.scene.paint.Color;
import javafx.scene.text.Font;
import javafx.scene.text.FontPosture;
import javafx.scene.text.FontWeight;
import javafx.stage.FileChooser;
import javafx.stage.Stage;
import javafx.scene.Scene;
import javafx.scene.layout.Pane;
import javafx.scene.shape.Rectangle;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;


public class PrisonerProfile extends Application {

    Stage ProfileStage = new Stage();
    private Label lblPrsProfile,lblPrisonerID,lblFName,lblMidName,lblLName,lblEntranceDate,lblReleaseDate;
    private Label lblSecuLevel,lblCellShare,lblCellNo,lblDateofBirth,lblMaritalStatus,lblBloodType,lblHealth,lblCrime;
    private RadioButton rbtSecLevelH,rbtSecLevelN,rbtCellShareY,rbtCellShareN,rbtSingle,rbtMarried,rbtDivorced;
    private RadioButton rbtA,rbtB,rbtAB,rbtO;
    private TextField txfPrsID,txfMS,txfFName, txfMidName, txfLName, txfSecLev, txfCellSh, txfCellNo,txfBlood;
    private DatePicker birthDate,dateEntry,dateRelease;
    private Button btnGoBack;
    private Rectangle ImgRect;
    private ImageView ImgView;
    private TextArea taHealth, taCrime;

    @Override
    public void start(Stage primaryStage){

        Pane ProfilePane = new Pane();

        lblPrsProfile = new Label("Prisoner Profile");
             lblPrsProfile.setLayoutX(40);
             lblPrsProfile.setLayoutY(20);
             lblPrsProfile.setFont(Font.font("Times New Roman", FontWeight.BOLD, FontPosture.REGULAR,20));
        lblPrisonerID = new Label("Prisoner ID");
             lblPrisonerID.setLayoutX(50);
             lblPrisonerID.setLayoutY(60);
             lblPrisonerID.setFont(Font.font("Times New Roman", FontWeight.BOLD, FontPosture.REGULAR,16));
        lblFName = new Label("FirstName");
             lblFName.setLayoutX(50);
             lblFName.setLayoutY(100);
             lblFName.setFont(Font.font("Times New Roman", FontWeight.BOLD, FontPosture.REGULAR,16));
        lblMidName = new Label("MiddleName");
             lblMidName.setLayoutX(50);
             lblMidName.setLayoutY(140);
             lblMidName.setFont(Font.font("Times New Roman", FontWeight.BOLD, FontPosture.REGULAR,16));
        lblLName = new Label("LastName");
             lblLName.setLayoutX(50);
             lblLName.setLayoutY(180);
             lblLName.setFont(Font.font("Times New Roman", FontWeight.BOLD, FontPosture.REGULAR,16));
        lblDateofBirth = new Label("Date of Birth");
        lblDateofBirth.setLayoutX(50);
        lblDateofBirth.setLayoutY(220);
        lblDateofBirth.setFont(Font.font("Times New Roman",FontWeight.BOLD,FontPosture.REGULAR,16));
        lblMaritalStatus = new Label("Marital Status");
        lblMaritalStatus.setLayoutX(50);
        lblMaritalStatus.setLayoutY(260);
        lblMaritalStatus.setFont(Font.font("Times New Roman",FontWeight.BOLD,FontPosture.REGULAR,16));
        lblEntranceDate = new Label("Entrance Date");
        lblEntranceDate.setLayoutX(50);
        lblEntranceDate.setLayoutY(330);
        lblEntranceDate.setFont(Font.font("Times New Roman", FontWeight.BOLD, FontPosture.REGULAR,16));
        lblReleaseDate = new Label("Release Date");
        lblReleaseDate.setLayoutX(50);
        lblReleaseDate.setLayoutY(370);
        lblReleaseDate.setFont(Font.font("Times New Roman", FontWeight.BOLD, FontPosture.REGULAR,16));
        lblSecuLevel = new Label("Security Level");
        lblSecuLevel.setLayoutX(50);
        lblSecuLevel.setLayoutY(410);
        lblSecuLevel.setFont(Font.font("Times New Roman", FontWeight.BOLD, FontPosture.REGULAR,16));
        lblCellShare = new Label("Cell Sharing");
        lblCellShare.setLayoutX(50);
        lblCellShare.setLayoutY(450);
        lblCellShare.setFont(Font.font("Times New Roman", FontWeight.BOLD, FontPosture.REGULAR,16));
        lblCellNo = new Label("Cell Number");
        lblCellNo.setLayoutX(50);
        lblCellNo.setLayoutY(490);
        lblCellNo.setFont(Font.font("Times New Roman", FontWeight.BOLD, FontPosture.REGULAR,16));
        lblBloodType = new Label("Blood Type");
        lblBloodType.setLayoutX(450);
        lblBloodType.setLayoutY(200);
        lblBloodType.setFont(Font.font("Times New Roman", FontWeight.BOLD, FontPosture.REGULAR,16));
        lblHealth = new Label("Health Information");
        lblHealth.setLayoutX(450);
        lblHealth.setLayoutY(230);
        lblHealth.setFont(Font.font("Times New Roman",FontWeight.BOLD,FontPosture.REGULAR,16));
        lblCrime = new Label("Crime Committed and Sentence Passed");
        lblCrime.setLayoutX(450);
        lblCrime.setLayoutY(320);
        lblCrime.setFont(Font.font("Times New Roman",FontWeight.BOLD,FontPosture.REGULAR,16));

        txfFName = new TextField();
        txfFName.setPrefColumnCount(15);
        txfFName.setLayoutX(180);
        txfFName.setLayoutY(100);
        txfFName.setEditable(false);
        txfMidName = new TextField();
        txfMidName.setPrefColumnCount(15);
        txfMidName.setLayoutX(180);
        txfMidName.setLayoutY(140);
        txfMidName.setEditable(false);
        txfLName = new TextField();
        txfLName.setPrefColumnCount(15);
        txfLName.setLayoutX(180);
        txfLName.setLayoutY(180);
        txfLName.setEditable(false);
        birthDate = new DatePicker();
        birthDate.setLayoutX(180);
        birthDate.setLayoutY(220);
        birthDate.setEditable(false);
        rbtSingle = new RadioButton("Single");
        rbtSingle.setLayoutX(180);
        rbtSingle.setLayoutY(260);
        rbtMarried = new RadioButton("Married");
        rbtMarried.setLayoutX(240);
        rbtMarried.setLayoutY(260);
        rbtDivorced = new RadioButton("Divorced");
        rbtDivorced.setLayoutX(310);
        rbtDivorced.setLayoutY(260);
        ToggleGroup tgMS = new ToggleGroup();
        rbtSingle.setToggleGroup(tgMS);
        rbtMarried.setToggleGroup(tgMS);
        rbtDivorced.setToggleGroup(tgMS);
        txfMS = new TextField();
        txfMS.setPrefColumnCount(8);
        txfMS.setLayoutX(180);
        txfMS.setLayoutY(290);
        txfMS.setEditable(false);
        dateEntry = new DatePicker();
        dateEntry.setLayoutX(180);
        dateEntry.setLayoutY(330);
        dateEntry.setEditable(false);
        dateRelease = new DatePicker();
        dateRelease.setLayoutX(180);
        dateRelease.setLayoutY(370);
        dateRelease.setEditable(false);
        rbtSecLevelH = new RadioButton("High");
        rbtSecLevelH.setLayoutX(180);
        rbtSecLevelH.setLayoutY(410);
        rbtSecLevelN = new RadioButton("Normal");
        rbtSecLevelN.setLayoutX(230);
        rbtSecLevelN.setLayoutY(410);
        ToggleGroup tgSecLev = new ToggleGroup();
        rbtSecLevelH.setToggleGroup(tgSecLev);
        rbtSecLevelN.setToggleGroup(tgSecLev);
        txfSecLev = new TextField();
        txfSecLev.setPrefColumnCount(5);
        txfSecLev.setLayoutX(300);
        txfSecLev.setLayoutY(410);
        txfSecLev.setEditable(false);
        rbtCellShareY = new RadioButton("Yes");
        rbtCellShareY.setLayoutX(180);
        rbtCellShareY.setLayoutY(450);
        rbtCellShareN = new RadioButton("No");
        rbtCellShareN.setLayoutX(230);
        rbtCellShareN.setLayoutY(450);
        ToggleGroup tgCellShare = new ToggleGroup();
        rbtCellShareY.setToggleGroup(tgCellShare);
        rbtCellShareN.setToggleGroup(tgCellShare);
        txfCellSh = new TextField();
        txfCellSh.setPrefColumnCount(5);
        txfCellSh.setLayoutX(300);
        txfCellSh.setLayoutY(450);
        txfCellSh.setEditable(false);
        txfCellNo = new TextField();
        txfCellNo.setPrefColumnCount(15);
        txfCellNo.setLayoutX(180);
        txfCellNo.setLayoutY(490);
        txfCellNo.setEditable(false);

         btnGoBack = new Button("Go Back");
             btnGoBack.setLayoutX(700);
             btnGoBack.setLayoutY(550);
             btnGoBack.setFont(Font.font("Courier",FontWeight.BOLD,FontPosture.REGULAR,14));
             btnGoBack.setOnAction(event -> {
                 Prisoner Pris = new Prisoner();
                    Pris.start(Pris.PrisonerStage);
                    ProfileStage.hide();
             });
        rbtA = new RadioButton("A");
        rbtA.setLayoutX(540);
        rbtA.setLayoutY(200);
        rbtB = new RadioButton("B");
        rbtB.setLayoutX(580);
        rbtB.setLayoutY(200);
        rbtAB = new RadioButton("AB");
        rbtAB.setLayoutX(620);
        rbtAB.setLayoutY(200);
        rbtO = new RadioButton("O");
        rbtO.setLayoutX(660);
        rbtO.setLayoutY(200);
        ToggleGroup tgBlood = new ToggleGroup();
        rbtA.setToggleGroup(tgBlood);
        rbtB.setToggleGroup(tgBlood);
        rbtAB.setToggleGroup(tgBlood);
        rbtO.setToggleGroup(tgBlood);
        txfBlood = new TextField();
        txfBlood.setLayoutX(700);
        txfBlood.setLayoutY(195);
        txfBlood.setPrefColumnCount(5);
        txfBlood.setEditable(false);
        taHealth = new TextArea();
        taHealth.setLayoutX(450);
        taHealth.setLayoutY(260);
        taHealth.setEditable(false);
        taHealth.setPrefSize(300,50);
        taCrime = new TextArea();
        taCrime.setLayoutX(450);
        taCrime.setLayoutY(350);
        taCrime.setEditable(false);
        taCrime.setPrefSize(300,50);
        ImgRect = new Rectangle(450,80,100,100);
        ImgRect.setStroke(Color.BLACK);
        ImgRect.setFill(Color.WHITE);
        Image img = new Image("imagesPP.jpeg");
        ImgView = new ImageView(img);
        ImgView.setFitHeight(99);
        ImgView.setFitWidth(99);
        ImgView.setLayoutX(450);
        ImgView.setLayoutY(80);

        ProfilePane.getChildren().addAll(lblPrsProfile,lblFName,lblMidName,lblLName,lblDateofBirth,lblMaritalStatus,lblEntranceDate,
                lblReleaseDate,lblSecuLevel,lblCellShare,lblCellNo,lblBloodType,lblHealth,lblCrime,txfFName,txfMidName,txfLName,birthDate,dateEntry,dateRelease,
                rbtSecLevelH,rbtSecLevelN,txfSecLev,rbtCellShareY,rbtCellShareN,rbtSingle,rbtMarried,rbtDivorced,txfMS,txfCellSh,
                txfCellNo,ImgRect,ImgView,btnGoBack,rbtA,rbtB,rbtAB,rbtO,txfBlood,taHealth,taCrime);


        Scene ProfileScene = new Scene(ProfilePane,800,600);

        ProfileStage.setTitle("Prisoner Profile");
        ProfileStage.setResizable(false);
        ProfileStage.setScene(ProfileScene);
        ProfileStage.show();
    }
}
